import { app } from '@appjoint/server';
import { headers } from 'next/headers';

let appJoint = app('Demo-app-hpdwq');

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let user = await appJoint.getUserFromHeaders(headers());

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        {user ? (
          children
        ) : (
          <form action="/api/login" method="post">
            <div>
              Email: <input name="email" type="email" />
            </div>

            <div>
              Password: <input name="password" type="password" />
            </div>

            <input type="submit" value="Login" />
          </form>
        )}
      </body>
    </html>
  );
}
