name: E2E Test
# disabled for now
# on: [pull_request]
on: []
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:app
          wait-on: 'http://localhost:1234'
          wait-on-timeout: 120
